export const SET_DESTINATIONS = 'SET_DESTINATIONS';
export const SET_FLIGHTS = 'SET_FLIGHTS';
export const SELECT_DEPARTURE = 'SELECT_DEPARTURE';
export const SELECT_ARRIVAL = 'SELECT_ARRIVAL';
export const SWAP_DEPARTURE_ARRIVAL = 'SWAP_DEPARTURE_ARRIVAL';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_DESTINATIONS_LOADING = 'SET_DESTINATIONS_LOADING';
export const SET_FLIGHTS_LOADING = 'SET_FLIGHTS_LOADING';

