export const SET_DESTINATIONS = 'SET_DESTINATIONS';
export const SET_PRICES = 'SET_PRICES';
export const SELECT_DESTINATION_FROM = 'SELECT_DESTINATION_FROM';
export const SELECT_DESTINATION_TO = 'SELECT_DESTINATION_TO';
