export const SET_DESTINATIONS = 'SET_DESTINATIONS';
export const SET_PRICES = 'SET_PRICES';
export const SELECT_DEPARTURE = 'SELECT_DEPARTURE';
export const SELECT_ARRIVAL = 'SELECT_ARRIVAL';
export const SWAP_DEPARTURE_ARRIVAL = 'SWAP_DEPARTURE_ARRIVAL';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
